//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrjWebCsProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int RefMsg { get; set; }
        public string MsgSender { get; set; }
        public string MsgReceiver { get; set; }
        public string MsgContent { get; set; }
    }
}
