//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrjWebCsProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string UserEmail { get; set; }
        public string UserPassword { get; set; }
        public string UserName { get; set; }
        public string UserGender { get; set; }
        public Nullable<System.DateTime> UserBirthDate { get; set; }
        public string UserRace { get; set; }
        public string UserCity { get; set; }
        public string UserLang { get; set; }
        public string UserPhoto { get; set; }
    }
}
